### ISSUE TITLE
Project Requirements 

### ISSUE THREAD

**Issue by matthall8** [DenisKent/week5AwesomeProject#1]
## Core Requirements
- [x] Use at least 1 API #3 
- [x] Make your API calls from the back-end using the Request module (or one you build yourself)
- [x] Your server should contain a minimum of 2 routes
- [ ] We expect back-end testing using Tape (test as many components as you can) and basic front-end testing.
- [x] Test your server by injecting fake HTTP requests using Supertest (consider testing for 404's and 500's). #8 
- [ ] Host your project on Heroku, see resources
- [x] Use module.exports and require to break a single large server file into smaller modules.
- [x] Consider a good server file structure based on what we have discussed over the week.
- [x] Employ continuous intergration on your project with Travis or a similar tool. (If you decide to use Travis, we strongly recommend that you host this project in your own repo rather than in your cohort's FAC repository to avoid all builds getting queued together) #15 
- [x] Use CodeCov or a similar tool for test coverage. 
- [x] Include Error Handling when a user attempts to make a request to a non-existent route to your server (404 - as mentioned above), provide the user with a custom response.
- [x] Include Error Handling if there is a programmer error on your server (e.g. a handler function does not act as intended, or receives a datatype it is not expecting), provide the user with a custom response (500 status code).
- [x] Include a user input field on your web app and include server-side validation to protect your server from potentially malicious user input. #25 

## Stretch goal 😊:
- [x] Create a route and functionality for a POST request #4 
- [ ] Display continuous intergration and code coverage badges on your project README. #10 
- [ ] Create hover tooltips for pollution types
- [ ] Apply Nielson's 10 Heuristics to the website design #9 
- [ ] Use grids when structuring the site
